version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hbs_data_processing_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
      - /rails/tmp
      - /rails/log
      - uploads_data:/rails/tmp/uploads
    command: bundle exec rails server -b 0.0.0.0

  sidekiq:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
      - /rails/tmp
      - /rails/log
      - uploads_data:/rails/tmp/uploads
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data:
  uploads_data:
